# execute
#      mvn exec:exec -Dconfig=bioasq.phase-b-train-answer-type
# to test the pipeline

configuration:
  name: phase-b-train-answer-type
  author: ziy

persistence-provider:
  inherit: baseqa.persistence.local-sqlite-persistence-provider

collection-reader:
  inherit: baseqa.collection.json.json-collection-reader
  dataset: BIOASQ-QA
  file:
    - input/dryrun-a.json
    - input/1b-1-a.json
    - input/1b-2-a.json
    - input/1b-3-a.json
    - input/2b-1-a.json
    - input/2b-2-a.json
    - input/2b-3-a.json
    - input/2b-4-a.json
    - input/2b-5-a.json
    - input/3b-1-a.json
    - input/3b-2-a.json
    - input/3b-3-a.json
    - input/3b-4-a.json
#    - input/3b-5-a.json
  type: [factoid, list]
  decorators: |
    - inherit: bioasq.gs.bioasq-qa-gs-decorator
  persistence-provider: |
    inherit: baseqa.persistence.local-sqlite-persistence-provider

pipeline:
  - inherit: ecd.phase
    name: question-parse
    options: |
      - inherit: bioqa.question.parse.clearnlp-bioinformatics

  - inherit: ecd.phase
    name: question-concept-metamap
    options: |
      - inherit: bioqa.question.concept.metamap-cached

  - inherit: ecd.phase
    name: question-concept-tmtool
    options: |
      - inherit: bioqa.question.concept.tmtool-cached

  - inherit: ecd.phase
    name: question-concept-lingpipe-genia
    options: |
      - inherit: bioqa.question.concept.lingpipe-genia

  - inherit: ecd.phase
    name: question-focus
    options: |
      - inherit: baseqa.question.focus

  - inherit: ecd.phase
    name: concept-search-uts
    options: |
      - inherit: bioqa.evidence.concept.search-uts-cached

  - inherit: ecd.phase
    name: concept-merge
    options: |
      - inherit: baseqa.evidence.concept.merge

  - inherit: ecd.phase
    name: answer-type
    options: |
      - inherit: bioqa.answer_type.liblinear-train
      - inherit: bioqa.answer_type.liblinear-null-train
#      - inherit: bioqa.answer_type.train-weka-reptree
#      - inherit: bioqa.answer_type.train-weka-reptree-null
#      - inherit: bioqa.answer_type.train-weka-knn
#      - inherit: bioqa.answer_type.train-weka-knn-null
#      - inherit: bioqa.answer_type.train-meka-pcc
#      - inherit: bioqa.answer_type.train-meka-pcc-null
