# execute
#      mvn exec:exec -Dconfig=bioasq.phase-a-test
# to test the pipeline

configuration:
  name: phase-a-test
  author: ziy

persistence-provider:
  inherit: baseqa.persistence.local-sqlite-persistence-provider

collection-reader:
  inherit: baseqa.collection.json.json-collection-reader
  dataset: BIOASQ-QA
  file:
#    - input/4b-1-a.json
#    - input/4b-2-a.json
#    - input/4b-3-a.json
#    - input/4b-4-a.json
    - input/4b-5-a.json
  persistence-provider: |
    inherit: baseqa.persistence.local-sqlite-persistence-provider

pipeline:
  - inherit: ecd.phase
    name: question-parse
    options: |
      - inherit: bioqa.question.parse.clearnlp-bioinformatics

  - inherit: ecd.phase
    name: question-concept-metamap
    options: |
      - inherit: bioqa.question.concept.metamap-cached

  - inherit: ecd.phase
    name: question-concept-tmtool
    options: |
      - inherit: bioqa.question.concept.tmtool-cached

  - inherit: ecd.phase
    name: question-concept-lingpipe-genia
    options: |
      - inherit: bioqa.question.concept.lingpipe-genia

  - inherit: ecd.phase
    name: concept-search-uts
    options: |
      - inherit: bioqa.evidence.concept.search-uts-cached

  - inherit: ecd.phase
    name: concept-merge
    options: |
      - inherit: baseqa.evidence.concept.merge

  - inherit: ecd.phase
    name: abstract-query-primary
    options: |
      - inherit: baseqa.abstract_query.token-concept

  # concept
  - inherit: ecd.phase
    name: concept-retrieval
    options: |
      - inherit: bioqa.concept.retrieval.lucene-bioconcept

  - inherit: ecd.phase
    name: concept-rerank
    options: |
      - inherit: bioqa.concept.rerank.liblinear-predict

  # document
  - inherit: ecd.phase
    name: document-retrieval
    options: |
      - inherit: bioqa.document.retrieval.lucene-medline

  - inherit: ecd.phase
    name: document-rerank
    options: |
      - inherit: bioqa.document.rerank.liblinear-predict

  # snippet
  - inherit: ecd.phase
    name: passage-retrieval
    options: |
      - inherit: bioasq.passage.retrieval.document-to-passage

  - inherit: ecd.phase
    name: passage-rerank
    options: |
      - inherit: bioqa.passage.rerank.liblinear-predict
      - inherit: base.noop

post-process:
  # submission
  - inherit: bioasq.collection.json.json-cas-consumer
