# execute
#      mvn exec:exec -Dconfig=bioasq.preprocess-answer-type-gslabel
# to test the pipeline

configuration:
  name: preprocess-answer-type-gslabel
  author: ziy

persistence-provider:
  inherit: baseqa.persistence.local-sqlite-persistence-provider

collection-reader:
  inherit: baseqa.collection.json.json-collection-reader
  dataset: BIOASQ-QA
  file:
    - input/dryrun-b.json
    - input/1b-1-b.json
    - input/1b-2-b.json
    - input/1b-3-b.json
    - input/2b-1-b.json
    - input/2b-2-b.json
    - input/2b-3-b.json
    - input/2b-4-b.json
    - input/2b-5-b.json
    - input/3b-1-b.json
    - input/3b-2-b.json
    - input/3b-3-b.json
    - input/3b-4-b.json
    - input/3b-5-b.json
  type: [factoid, list]
  decorators: |
    - inherit: bioasq.gs.bioasq-qa-gs-decorator
  persistence-provider: |
    inherit: baseqa.persistence.local-sqlite-persistence-provider

pipeline:
  - inherit: ecd.phase
    name: question-parse
    options: |
      - inherit: bioqa.question.parse.clearnlp-bioinformatics

  - inherit: ecd.phase
    name: answer-type-gslabel-uts
    options: |
      - inherit: bioqa.answer_type.gslabel-uts

  - inherit: ecd.phase
    name: answer-type-gslabel-tmtool
    option-timeout: 30
    options: |
      - inherit: bioqa.answer_type.gslabel-tmtool